AllCops:
  Include:
    - Rakefile
    - Gemfile
    - config.ru
  Exclude:
    - tmp/**/*
    - db/**/*
    - bin/**/*
    - scripts/**/*

Rails:
  Enabled: true

Rails/Output:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Documentation:
  Enabled: false

Style/DateTime:
  Enabled: false

Lint/ShadowedException:
  Enabled: false
