AllCops:
  Include:
    - Rakefile
    - Gemfile
    - config.ru
    - '**/*.rb'
    - '**/*.spec'
  Exclude:
    - tmp/**/*
    - db/**/*
    - bin/**/*
    - scripts/**/*
    - vendor/**/*
    - lib/rets.rb
    - lib/rets/**/*
    - spec/support/graphql_spec_helper.rb
    - schema.json

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/DateTime:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Style/Lambda:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
